# Generated by Django 5.1.1 on 2024-09-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='user',
            new_name='owner',
        ),
    ]
