# Generated by Django 5.1.1 on 2024-09-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_user_subject_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='user',
            new_name='owner',
        ),
    ]
