# Generated by Django 5.1.1 on 2024-09-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_question_owner_question_note_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_quiz_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
