# Generated by Django 5.1.1 on 2024-09-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_is_quiz_done_note_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='enriched_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
