# Generated by Django 5.1.1 on 2024-09-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_enriched_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file',
        ),
    ]
