# Generated by Django 5.1.1 on 2024-09-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='Is note fully processed'),
        ),
    ]
