# Generated by Django 5.1.1 on 2024-09-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_note_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_listened',
            field=models.BooleanField(default=False),
        ),
    ]
