# Generated by Django 5.1.1 on 2024-09-29 07:20

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=notes.models.get_file_upload_path),
        ),
    ]
