# Generated by Django 5.1.1 on 2024-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_note_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.CharField(default='fotosynteza', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(default='Przyroda', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
